version: '3'
services:
  server:
    image: grpc
    user: ${CURRENT_UID}
    entrypoint: /bin/bash
    command: -c "export PYTHONPATH=`pwd`/src/pb:$${PYTHONPATH} && python3 server/server.py"
    working_dir: /server
    volumes:
    - .:/server
  server_reverse_proxy:
    image: grpc
    user: ${CURRENT_UID}
    entrypoint: /bin/bash
    command: -c "sleep 2 && echo server_reverse_proxy && export GOPATH=`pwd`:$${GOPATH} && go run server/server-rproxy.go"
    working_dir: /server
    volumes:
    - .:/server
    - .cache:/.cache
    ports:
    - 8080:8080
    depends_on:
    - server
