version: '3'
services:
  client:
    image: grpc
    user: ${CURRENT_UID}
    entrypoint: /bin/bash
    command: -c "sleep 5 && curl --silent -X POST -k http://server_reverse_proxy:8080/v1/example/echo -d '{\"msg\":\"Hello world\",\"id\":\"666\"}'"
    depends_on:
    - server_reverse_proxy
